Выполняет практическое задание
htmlacademy-javascript/170610-code-and-magick-21 pull request #1
Opened 2020-09-16 09:52 UTC by avedmigen

2020-09-17 17:28 UTC, artem-Zrilov requested changes

2020-09-17 17:28 UTC, artem-Zrilov commented on index.html
> +  let getWizardX = gameFieldWidth => gameFieldWidth - wizardWidth / 2;
Вычитание нужно обернуть в скобки сейчас не правильный расчет

2020-09-18 05:27 UTC, avedmigen commented on index.html
> +  let getWizardX = gameFieldWidth => gameFieldWidth - wizardWidth / 2;
Спасибо. Исправлено 53cb478aa02c8b666fca8d2eb717a9c4fb7ca28e

2020-09-18 07:54 UTC, artem-Zrilov approved these changes

2020-09-18 07:54 UTC, merged